---
title: "Projects and Lab 03"
author: "AG Schissler"
date: "Wednesday September 25, 2019"
output: html_document
---

## I. Opening 

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE, cache.comments=TRUE)
```

### Start-of-class work

1. Log in the your workstation.
2. Open the RStudio application on your machine.
3. Open our meeting agenda [lab_03_ttest_text_parallel.Rmd](https://github.com/grizant/STAT445/blob/master/labs/lab_03_ttest_text_parallel.Rmd) from website so that you can work along the lecture.

## II. Projects

Please email your initial project groups by the end of the day. 

### Project ideas

1) you have a data set you'd like to analyze 
2) you have a applied topic you'd like to find publicly available data for and analyze
3) you would like to analyze real data that I have on hand --- medical data, environmental data, genetic data. Possibly in a collaboration with other out-of-class students leading the project.
4) you have a stats computing method/concept you'd like to explore (check out the later topics in our course schedule for some ideas). Or ask me for an idea here.

## III. Labs

Let's review the lab rubric/checklist. 

- [Lab rubric](https://github.com/grizant/STAT445/blob/master/rubrics/lab_rubric.pdf)
- [Lab checklist](https://github.com/grizant/STAT445/blob/master/checklists/lab_checklist.pdf)

Also Alex K. provided a new template/more guidance:

- [sample_lab_report.Rmd](https://github.com/grizant/STAT445/blob/master/labs/sample_lab_report.Rmd)
- [sample_lab_report.html](http://www.grantschissler.com/teaching/FA19/STAT445/sample_lab_report.html)

### Please continue working Lab 03

- [lab_03_ttest_text_parallel.Rmd](https://github.com/grizant/STAT445/blob/master/labs/lab_03_ttest_text_parallel.Rmd)

### IV. Summary: 

- How will you improve your lab reports?  
