---
title: "Lab 07: Exploring data with ggplot2"
author: "AG Schissler (modified from Ryan Tibshirani)"
date: "Week of 10/29/2018"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE, cache.comments=TRUE)
set.seed(44)
```

Name:  
NSHE ID:  
Collaborated with:  

This lab is to be done in class (completed outside of class if need be). You can collaborate with your classmates, but you must identify their names above, and you must submit **your own** lab as an knitted HTML file on Canvas, by Sunday 11:59pm, this week.

Learning outcomes
===

Students will be able to use advanced R plotting tools, including ggplot2
Students will be able to apply the concept of vizualization layers (grammer of graphics)

STAT 645 Project milestone (20 point deduction if not completed)
===

Prepare a data analysis plan by answering the following:
1. What model(s) will you use?
2. What computational statistical inferenece technique(s) wille you use? E.g., randomization tests, resampling, MCMC, etc.
3. How will your analysis relate to your research questions?
4. Do you anticipate any problems with your proposed approach? If so, how will you rememdy these issues?
